### ISSUE TITLE
Q: Support for .NET Core?

### ISSUE THREAD

**Issue by pardahlman** [d-collab/RabbitMqNext#10]
The `RabbitMqnext`NuGet only supports `4.6.1`, are there any plans to support .NET Core?

**Comment by hammett** [comment]
Sure, once they RTM.

**Comment by pardahlman** [comment]
That is great news :ok_hand: According to the [Roadmap](https://github.com/aspnet/Home/wiki/Roadmap) it should be within weeks.

**Comment by pardahlman** [comment]
@hammett any progresson this issue?

**Comment by DaveVdE** [comment]
There's a pre-release package that I'm using. I found it on this NuGet feed: https://ci.appveyor.com/nuget/rabbitmq-dotnet-client-ci

**Comment by hammett** [comment]
@pardahlman I'm not planning on doing it myself. I'm open to a PR that adapts the code. We dont use core here, so it makes no economic sense to put our resources into it.

**Comment by brownpurchase** [comment]
Wow...  this wasn't written by a c# developer was it?  I am trying to convert but it would have to be a complete rewrite and I don't have any integration tests to be able to verify I am not doing something wrong.

**Comment by hammett** [comment]
Maybe these would help: https://github.com/clearctvm/RabbitMqNext/tree/master/test

**Comment by grandchamp** [comment]
That's not so hard to convert to NETStandard 2.0. I did, but i renamed all internal to public (i was having some compilation errors).
Some tests was commented too.

https://github.com/grandchamp/RabbitMqNext/commit/9ab3075c7fa2d2b79c58b5fe2dee56c1387aef2b

**Comment by grandchamp** [comment]
But it sounds that your lib messes up with .NET Core routing (app.Map or even MVC).
All my endpoints are returning 404.
